SELECT LPAD(NVL(MC.COD_BARRAS,0),13,'0')CODIGO,
TO_CHAR(NVL(MAN_EST_RETORNA_SALDO(PI_EMPR_ID,ITE.ITEM_ID,'PI_COD_ALMOX',SYSDATE),0),'FM00000000D00') SALDO
FROM TINT_PRODUTOS_MICROVIX MC,
TITENS_EMPR ITE
WHERE ITE.EMPR_ID = FOCCO3I_UTIL.RETORNA_PARAMETRO('INT_MICROVIX', 'EMPRESA_PADRAO', NULL, NULL)
AND ITE.COD_ITEM = MC.REFERENCIA
--AND ITE.COD_ITEM = 'UT018'
--AND MC.DESATIVADO = 0